## BeOS Generic Makefile v2.2 ##
NAME = ../KeyCursor
TYPE = APP
SRCS = \
	KeyCursorSettings.cpp \
	ModifierBox.cpp \
	ModifierView.cpp \
	../src/Preferences.cpp \
	SettingsWin.cpp
RSRCS = KeyCursor.rsrc
LIBS = be
# stdc++.r4
LIBPATHS =
SYSTEM_INCLUDE_PATHS =
LOCAL_INCLUDE_PATHS = ../src/
OPTIMIZE = FULL
DEFINES = I_AM_THE_PREFLET
WARNINGS =
SYMBOLS =
DEBUGGER =
COMPILER_FLAGS =
LINKER_FLAGS = -s

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
