## BeOS Generic Makefile v2.2 ##
NAME = ../KeyCursor
TYPE = SHARED
SRCS = \
	KeyCursorDevice.cpp	\
	KeyCursorFilter.cpp \
	Preferences.cpp
RSRCS =
LIBS = be _APP_
LIBPATHS =
SYSTEM_INCLUDE_PATHS =
LOCAL_INCLUDE_PATHS = 
OPTIMIZE = FULL
DEFINES =
WARNINGS = ALL
SYMBOLS =
DEBUGGER =
COMPILER_FLAGS =
LINKER_FLAGS = -s

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
